[[main]]
name = "Úvod"
url = "/"
weight = 10

[[main]]
identifier = "services"
name = "Služby"
url = "#"
weight = 20

[[main]]
name = "IT Blog"
url = "/blog/"
weight = 40

[[main]]
name = "Kontakty"
url = "/#contact"
weight = 80

[[footer]]
identifier = "website"
name = "DevOps IT"
url = "#"
weight = 10

[[footer]]
parent = "website"
name = "Úvod"
url = "/"
weight = 10

[[footer]]
parent = "website"
name = "Služby"
url = "/consulting/"
weight = 20

[[footer]]
parent = "website"
name = "Kontakty"
url = "/#contact"
weight = 30

[[footer]]
identifier = "hosting"
name = "Zdroje vědomostí"
url = "#"
weight = 20

[[footer]]
parent = "hosting"
name = "IT Blog"
url = "/blog/"
weight = 10

[[services]]
name = "IT Konzultace"
url = "/consulting/"
weight = 10
[services.params]
icon = "uil uil-chart-line"

[[services]]
name = "IT Vývoj"
url = "/#development"
weight = 20
[services.params]
icon = "uil uil-desktop"

[[services]]
name = "IT Know-HOW"
url = "/#training"
weight = 30
[services.params]
icon = "uil uil-graduation-cap"
