baseURL = "https://azarethcz.github.io/"
locale = "en-US"
title = "Moje Portfolio"
theme = "careercanvas"
diablePostCSS = true

[pagination]
pagerSize = 5

[params.pexels]
queries = ["technology", "developer", "cloud"]
