baseURL = "https://azarethcz.github.io/"
locale = "en-US"
title = "Azareth Portfolio"
theme = "blunix"

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Azareth"
Content = "DevOps Engineer | Kubernetes | Rancher | CI/CD | AutoPilot OPS"

[[params.socialIcons]]
name = "github"
url = "https://github.com/azarethcz"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com"
